#!/usr/bin/env python3
"""
Sanitize FlashInfer level-3 (or higher) API logs into per-API workload JSONL files.

Reads a log file produced by FlashInfer's `@flashinfer_api` decorator with
``FLASHINFER_LOGLEVEL=3`` (or higher) and emits one JSONL file per FlashInfer API
that appears in the log. Each line is a workload-style entry whose tensor inputs
are marked as ``type: random``. Non-tensor inputs are captured as ``scalar``,
``enum``, or ``literal`` descriptors.

If a directory of FlashInfer trace-dump definition JSONs is supplied via
``--trace-dir`` (e.g. files generated by ``@flashinfer_api(trace=...)`` +
``FLASHINFER_TRACE_DUMP=1``), the script tries to align each log call to a
matching definition: log tensors are mapped to the definition's named inputs,
``var`` axes are resolved from concrete shapes, and ``const`` axes are validated.
Matched workloads carry the definition name and use named ``random`` inputs
(no embedded shape — the schema lives in the definition). Unmatched calls fall
back to a raw, schema-less form keyed by ``arg_N`` / ``kwarg_NAME`` with the
shape/dtype embedded inline.

Usage:
    FLASHINFER_LOGLEVEL=3 FLASHINFER_LOGDEST=fi.log python my_script.py
    python scripts/sanitize_fi_log.py \\
        --log-file fi.log \\
        --output-dir workloads_from_log/ \\
        [--trace-dir tests/trace/fi_trace_out/]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import uuid
from collections import defaultdict
from pathlib import Path
from typing import Any, Iterable

# A log block looks like:
#   ================================================================================
#   [2026-05-01 10:30:00] FlashInfer API Call: BatchDecodeWithPagedKVCacheWrapper.run
#   --------------------------------------------------------------------------------
#   Positional input arguments:
#     arg[0]:
#       Tensor(
#         shape=(64, 4, 128)
#         stride=(512, 128, 1)
#         dtype=torch.bfloat16
#         ...
#       )
#   Keyword input arguments:
#     pos_encoding_mode=
#       PosEncodingMode.NONE (value=0)
#   Default parameters (not explicitly provided):
#     return_lse= [DEFAULT]
#       False
#   Output value:
#     Tensor(...)
#   ================================================================================

API_CALL_RE = re.compile(r"^\[\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\] FlashInfer API Call: (.+)$")
SEPARATOR_RE = re.compile(r"^=+\s*$")
ARG_HEADER_RE = re.compile(r"^  arg\[(\d+)\]:\s*$")
KWARG_HEADER_RE = re.compile(r"^  ([A-Za-z_]\w*)=(?:\s*\[DEFAULT\])?\s*$")

_SECTION_LABELS = {
    "Positional input arguments:": "positional",
    "Keyword input arguments:": "keyword",
    "Default parameters (not explicitly provided):": "default",
    "Output value:": "output",
    "(No explicit arguments)": "no_args",
}


# ---------------------------------------------------------------------------
# Log parsing
# ---------------------------------------------------------------------------


def _normalize_dtype(raw: str) -> str:
    raw = raw.strip()
    return raw[len("torch.") :] if raw.startswith("torch.") else raw


def _parse_int_tuple(raw: str) -> list[int]:
    """Parse strings like '(64, 4, 128)' or '(3,)' into a list of ints."""
    raw = raw.strip()
    if raw.startswith("(") and raw.endswith(")"):
        raw = raw[1:-1]
    parts = [p.strip() for p in raw.split(",") if p.strip()]
    return [int(p) for p in parts]


def _parse_tensor_block(value_lines: list[str]) -> dict[str, Any]:
    """Convert a Tensor(...) block into a random-input descriptor."""
    info: dict[str, Any] = {"type": "random"}
    for ln in value_lines[1:]:
        s = ln.strip()
        if s.startswith("shape="):
            info["shape"] = _parse_int_tuple(s[len("shape=") :])
        elif s.startswith("dtype="):
            info["dtype"] = _normalize_dtype(s[len("dtype=") :])
    if "shape" not in info:
        return {"type": "literal", "repr": "\n".join(value_lines)}
    return info


def _parse_scalar(first: str) -> dict[str, Any] | None:
    if first == "None":
        return {"type": "scalar", "value": None}
    if first in ("True", "False"):
        return {"type": "scalar", "value": first == "True"}
    try:
        return {"type": "scalar", "value": int(first)}
    except ValueError:
        pass
    try:
        return {"type": "scalar", "value": float(first)}
    except ValueError:
        pass
    if len(first) >= 2 and first[0] == first[-1] and first[0] in ("'", '"'):
        return {"type": "scalar", "value": first[1:-1]}
    return None


def _parse_value_block(value_lines: list[str]) -> dict[str, Any]:
    if not value_lines:
        return {"type": "scalar", "value": None}

    first = value_lines[0].strip()

    if first.startswith("Tensor("):
        return _parse_tensor_block(value_lines)

    if first.startswith("FP4Tensor("):
        return {"type": "literal", "kind": "FP4Tensor", "repr": "\n".join(value_lines)}

    enum_match = re.match(r"^([\w.]+)\.(\w+) \(value=(.+)\)$", first)
    if enum_match:
        return {
            "type": "enum",
            "name": f"{enum_match.group(1)}.{enum_match.group(2)}",
            "value_repr": enum_match.group(3),
        }

    scalar = _parse_scalar(first)
    if scalar is not None:
        return scalar

    return {"type": "literal", "repr": "\n".join(value_lines)}


def _iter_blocks(lines: list[str]) -> Iterable[tuple[str, list[str]]]:
    """Yield (function_name, block_body_lines) for every API call in the log."""
    n = len(lines)
    i = 0
    while i < n:
        m = API_CALL_RE.match(lines[i])
        if not m:
            i += 1
            continue
        func_name = m.group(1).strip()
        i += 1
        body: list[str] = []
        while i < n:
            ln = lines[i]
            if SEPARATOR_RE.match(ln):
                i += 1
                break
            if API_CALL_RE.match(ln):
                # Inputs-only block (e.g. crash before output) — start of next call.
                break
            body.append(ln)
            i += 1
        yield func_name, body


def _iter_inputs(body: list[str], include_defaults: bool) -> Iterable[tuple[str, list[str]]]:
    """Walk a block's body, yielding (input_name, value_lines) pairs."""
    section: str | None = None
    i = 0
    n = len(body)
    while i < n:
        line = body[i]
        stripped = line.strip()
        leading = len(line) - len(line.lstrip())

        if leading == 0 and stripped in _SECTION_LABELS:
            section = _SECTION_LABELS[stripped]
            i += 1
            continue

        if section in (None, "output", "no_args"):
            i += 1
            continue
        if section == "default" and not include_defaults:
            i += 1
            continue
        if section not in ("positional", "keyword", "default"):
            i += 1
            continue

        name: str | None = None
        m_arg = ARG_HEADER_RE.match(line)
        m_kw = KWARG_HEADER_RE.match(line)
        if m_arg:
            name = f"arg_{m_arg.group(1)}"
        elif m_kw:
            prefix = "default_" if section == "default" else "kwarg_"
            name = f"{prefix}{m_kw.group(1)}"

        if name is None:
            i += 1
            continue

        i += 1
        value_lines: list[str] = []
        while i < n:
            vl = body[i]
            if not vl.strip():
                i += 1
                continue
            vlead = len(vl) - len(vl.lstrip())
            if vlead <= 2:
                break
            value_lines.append(vl)
            i += 1

        yield name, value_lines


# ---------------------------------------------------------------------------
# Trace-definition loading & alignment
# ---------------------------------------------------------------------------


def _load_definitions(trace_dir: Path) -> dict[str, list[dict[str, Any]]]:
    """Index trace-dumped definitions by the qualname suffix of their fi_api tag.

    A trace JSON typically tags itself like ``fi_api:flashinfer.norm.rmsnorm``
    or ``fi_api:flashinfer.prefill.BatchPrefillWithRaggedKVCacheWrapper.run``.
    The log only shows the function/method qualname (``rmsnorm`` or
    ``BatchPrefillWithRaggedKVCacheWrapper.run``). We index every suffix so a
    log lookup can match either form.
    """
    index: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for path in sorted(trace_dir.glob("*.json")):
        try:
            defn = json.loads(path.read_text())
        except (OSError, json.JSONDecodeError) as exc:
            print(f"warning: skipping {path}: {exc}", file=sys.stderr)
            continue
        if not isinstance(defn, dict) or "inputs" not in defn:
            continue
        fi_apis = [
            tag[len("fi_api:") :]
            for tag in defn.get("tags", [])
            if isinstance(tag, str) and tag.startswith("fi_api:")
        ]
        keys: set[str] = set()
        for fi_api in fi_apis:
            parts = fi_api.split(".")
            for i in range(len(parts)):
                keys.add(".".join(parts[i:]))
        for key in keys:
            if defn not in index[key]:
                index[key].append(defn)
    return index


def _candidate_definitions(
    api_name: str, index: dict[str, list[dict[str, Any]]]
) -> list[dict[str, Any]]:
    return list(index.get(api_name, []))


def _split_def_inputs(defn: dict[str, Any]) -> tuple[dict[str, dict], dict[str, dict]]:
    tensor_inputs: dict[str, dict] = {}
    scalar_inputs: dict[str, dict] = {}
    for name, spec in defn.get("inputs", {}).items():
        if not isinstance(spec, dict):
            continue
        if spec.get("shape") is None:
            scalar_inputs[name] = spec
        else:
            tensor_inputs[name] = spec
    return tensor_inputs, scalar_inputs


def _consistent_with(
    log_input: dict[str, Any], def_spec: dict[str, Any], axes_bound: dict[str, int]
) -> bool:
    """Check whether a log tensor descriptor is compatible with a def input spec."""
    log_shape = log_input.get("shape")
    def_shape = def_spec.get("shape")
    if not isinstance(log_shape, list) or not isinstance(def_shape, list):
        return False
    if len(log_shape) != len(def_shape):
        return False
    def_dtype = def_spec.get("dtype", "")
    log_dtype = log_input.get("dtype", "")
    if def_dtype and def_dtype != "unknown" and def_dtype != log_dtype:
        return False
    for log_dim, def_dim in zip(log_shape, def_shape):
        if isinstance(def_dim, int):
            if def_dim != log_dim:
                return False
        elif isinstance(def_dim, str):
            if def_dim in axes_bound and axes_bound[def_dim] != log_dim:
                return False
    return True


def _bind_axes(
    log_input: dict[str, Any], def_spec: dict[str, Any], axes_bound: dict[str, int]
) -> None:
    for log_dim, def_dim in zip(log_input["shape"], def_spec["shape"]):
        if isinstance(def_dim, str) and def_dim not in axes_bound:
            axes_bound[def_dim] = log_dim


def _align_to_definition(
    defn: dict[str, Any], log_inputs: dict[str, dict[str, Any]]
) -> dict[str, Any] | None:
    """Try to align log inputs to a definition's named inputs.

    Returns a workload-shaped dict (axes + named inputs) on success, ``None``
    if the definition is incompatible with this call.
    """
    def_tensors, def_scalars = _split_def_inputs(defn)
    axes = defn.get("axes", {})
    axes_bound: dict[str, int] = {
        name: spec["value"]
        for name, spec in axes.items()
        if isinstance(spec, dict) and spec.get("type") == "const" and "value" in spec
    }

    tensor_log_inputs = {k: v for k, v in log_inputs.items() if v.get("type") == "random"}

    mapping: dict[str, str] = {}  # log_key -> def_input_name
    log_remaining = set(tensor_log_inputs)
    def_remaining = set(def_tensors)

    # Pass 1: name-match (kwarg name matches input name).
    for log_key in list(log_remaining):
        base = log_key
        for prefix in ("kwarg_", "default_"):
            if log_key.startswith(prefix):
                base = log_key[len(prefix) :]
                break
        if base in def_remaining and _consistent_with(
            tensor_log_inputs[log_key], def_tensors[base], axes_bound
        ):
            mapping[log_key] = base
            _bind_axes(tensor_log_inputs[log_key], def_tensors[base], axes_bound)
            log_remaining.discard(log_key)
            def_remaining.discard(base)

    # Pass 2: shape-match — assign uniquely-shape-compatible log tensors greedily.
    progressed = True
    while progressed and def_remaining:
        progressed = False
        for def_name in list(def_remaining):
            cands = [
                log_key
                for log_key in log_remaining
                if _consistent_with(tensor_log_inputs[log_key], def_tensors[def_name], axes_bound)
            ]
            if len(cands) == 1:
                log_key = cands[0]
                mapping[log_key] = def_name
                _bind_axes(tensor_log_inputs[log_key], def_tensors[def_name], axes_bound)
                log_remaining.discard(log_key)
                def_remaining.discard(def_name)
                progressed = True

    # Pass 3: positional-order fallback for symmetric inputs (e.g.
    # fused_add_rmsnorm has two interchangeable [batch, hidden] tensors that
    # neither name-match nor unique-shape-match can disambiguate). Pair the
    # remaining positional log args against the remaining def inputs in their
    # declaration order, accepting only if every pair is shape/dtype consistent.
    pos_remaining = sorted(
        (k for k in log_remaining if k.startswith("arg_")), key=lambda k: int(k.split("_", 1)[1])
    )
    if pos_remaining and def_remaining:
        def_in_order = [n for n in def_tensors if n in def_remaining]
        if len(pos_remaining) >= len(def_in_order):
            trial_axes = dict(axes_bound)
            trial_assign: list[tuple[str, str]] = []
            ok = True
            for def_name, log_key in zip(def_in_order, pos_remaining):
                if not _consistent_with(
                    tensor_log_inputs[log_key], def_tensors[def_name], trial_axes
                ):
                    ok = False
                    break
                _bind_axes(tensor_log_inputs[log_key], def_tensors[def_name], trial_axes)
                trial_assign.append((log_key, def_name))
            if ok:
                axes_bound.update(trial_axes)
                for log_key, def_name in trial_assign:
                    mapping[log_key] = def_name
                    log_remaining.discard(log_key)
                    def_remaining.discard(def_name)

    # Required def inputs must all be matched (optional ones may stay unbound).
    for def_name in def_remaining:
        if not def_tensors[def_name].get("optional", False):
            return None

    # Var axes that appear in a matched input must be bound. Axes that only
    # appear in unmatched optional inputs (e.g. plan-time indptrs that aren't
    # in a run() call's args) are simply omitted from the workload's axes.
    matched_def_names = set(mapping.values())
    axes_in_matched: set[str] = set()
    for def_name in matched_def_names:
        for dim in def_tensors[def_name].get("shape", []) or []:
            if isinstance(dim, str):
                axes_in_matched.add(dim)
    for axis_name in axes_in_matched:
        spec = axes.get(axis_name, {})
        if isinstance(spec, dict) and spec.get("type") == "var" and axis_name not in axes_bound:
            return None

    # Build the workload's inputs dict.
    named_inputs: dict[str, Any] = {}
    for log_key, def_name in mapping.items():
        named_inputs[def_name] = {"type": "random"}

    # Match scalar def inputs by kwarg name; copy the captured value.
    for def_name in def_scalars:
        for log_key in (f"kwarg_{def_name}", f"default_{def_name}"):
            if log_key in log_inputs and log_inputs[log_key].get("type") == "scalar":
                named_inputs[def_name] = {"type": "scalar", "value": log_inputs[log_key]["value"]}
                break

    var_axes = {
        name: axes_bound[name]
        for name, spec in axes.items()
        if (isinstance(spec, dict) and spec.get("type") == "var" and name in axes_bound)
    }

    return {"axes": var_axes, "inputs": named_inputs}


# ---------------------------------------------------------------------------
# Workload assembly
# ---------------------------------------------------------------------------


def _build_raw_workload(func_name: str, log_inputs: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    """Build a raw (unmatched) workload entry keyed by api name."""
    record = {
        "definition": None,
        "workload": {"uuid": str(uuid.uuid4()), "api": func_name, "inputs": log_inputs},
        "solution": null_value(),
        "evaluation": null_value(),
    }
    return func_name, record


def null_value() -> Any:
    # Tiny helper so the JSON output renders ``null`` rather than ``"null"``.
    return None


def _build_matched_workload(
    defn: dict[str, Any], aligned: dict[str, Any]
) -> tuple[str, dict[str, Any]]:
    record = {
        "definition": defn["name"],
        "workload": {
            "uuid": str(uuid.uuid4()),
            "axes": aligned["axes"],
            "inputs": aligned["inputs"],
        },
        "solution": None,
        "evaluation": None,
    }
    return defn["name"], record


def _align_lenient(
    defn: dict[str, Any], log_inputs: dict[str, dict[str, Any]]
) -> dict[str, Any] | None:
    """Best-effort alignment used when strict matching fails for every candidate.

    Maps log kwargs to def inputs by name. Const axes that are *directly
    bindable* (rank-matched assignments) must agree, otherwise the candidate
    is rejected. Rank-mismatched assignments still attach the input (with
    ``type: random``) but skip axis binding for that input — this is what
    lets MLA-style rank-collapsed tensors (k_rope ``[nnz, rope_dim]`` vs.
    schema ``[nnz, num_k_heads, rope_dim]``) align to their template.
    """
    def_tensors, def_scalars = _split_def_inputs(defn)
    axes = defn.get("axes", {})
    const_axes = {
        name: spec["value"]
        for name, spec in axes.items()
        if isinstance(spec, dict) and spec.get("type") == "const" and "value" in spec
    }
    axes_bound = dict(const_axes)
    named_inputs: dict[str, Any] = {}
    clean_matches = 0  # count of inputs that match cleanly (rank + const consistent)

    for log_key, desc in log_inputs.items():
        if desc.get("type") != "random":
            continue
        base = log_key
        for prefix in ("kwarg_", "default_", "arg_"):
            if log_key.startswith(prefix):
                base = log_key[len(prefix) :]
                break
        if base not in def_tensors:
            continue

        log_shape = desc.get("shape", [])
        def_shape = def_tensors[base].get("shape", []) or []
        if (
            isinstance(log_shape, list)
            and isinstance(def_shape, list)
            and len(log_shape) == len(def_shape)
        ):
            const_conflict = any(
                isinstance(def_dim, str)
                and def_dim in const_axes
                and const_axes[def_dim] != log_dim
                for log_dim, def_dim in zip(log_shape, def_shape)
            )
            if not const_conflict:
                clean_matches += 1
                for log_dim, def_dim in zip(log_shape, def_shape):
                    if isinstance(def_dim, str) and def_dim not in axes_bound:
                        axes_bound[def_dim] = log_dim
        named_inputs[base] = {"type": "random"}

    for def_name in def_scalars:
        for log_key in (f"kwarg_{def_name}", f"default_{def_name}"):
            if log_key in log_inputs and log_inputs[log_key].get("type") == "scalar":
                named_inputs[def_name] = {"type": "scalar", "value": log_inputs[log_key]["value"]}
                break

    required_tensor_inputs = {
        name for name, spec in def_tensors.items() if not spec.get("optional", False)
    }
    matched_required = required_tensor_inputs & set(named_inputs)
    # Require at least one required tensor matched AND at least one cleanly
    # rank+const-consistent input — guards against accidentally aligning to a
    # template that happens to share a kwarg name but is otherwise unrelated.
    if not matched_required or clean_matches == 0:
        return None

    var_axes = {
        name: axes_bound[name]
        for name, spec in axes.items()
        if (isinstance(spec, dict) and spec.get("type") == "var" and name in axes_bound)
    }
    return {"axes": var_axes, "inputs": named_inputs}


def _select_match(
    api_name: str,
    log_inputs: dict[str, Any],
    index: dict[str, list[dict[str, Any]]],
    *,
    strict_only: bool = False,
) -> tuple[dict[str, Any], dict[str, Any]] | None:
    candidates = _candidate_definitions(api_name, index)
    for defn in candidates:
        aligned = _align_to_definition(defn, log_inputs)
        if aligned is not None:
            return defn, aligned
    if strict_only:
        return None
    # Strict alignment failed for every candidate — fall back to name-based
    # alignment that tolerates schema/runtime discrepancies (e.g. MLA-style
    # rank collapse) but still rejects candidates whose const axes contradict
    # the log shapes.
    for defn in candidates:
        aligned = _align_lenient(defn, log_inputs)
        if aligned is not None:
            return defn, aligned
    return None


def _slugify(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "_", name)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Convert FlashInfer level-3 logs into per-API workload JSONL files."
    )
    parser.add_argument(
        "--log-file",
        required=True,
        type=Path,
        help="Path to a FlashInfer log produced with FLASHINFER_LOGLEVEL>=3.",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        type=Path,
        help="Directory to write per-API workload JSONL files into.",
    )
    parser.add_argument(
        "--trace-dir",
        type=Path,
        default=None,
        help=(
            "Optional directory of FlashInfer trace-dumped definition JSONs. "
            "When supplied, log calls are aligned to matching definitions and "
            "emitted with named inputs + resolved axes."
        ),
    )
    parser.add_argument(
        "--include-defaults",
        action="store_true",
        help="Also emit default-valued parameters (skipped by default).",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help=(
            "Strict matching only: skip the lenient name-based fallback. "
            "Calls that don't fully align (rank/const) to a candidate "
            "definition are emitted as raw."
        ),
    )
    parser.add_argument(
        "--dedupe",
        action="store_true",
        help=(
            "Collapse duplicate calls (same shapes/dtypes/scalars) into one entry "
            "per API/definition. Off by default — every call becomes a workload."
        ),
    )
    args = parser.parse_args()

    if not args.log_file.is_file():
        print(f"error: log file not found: {args.log_file}", file=sys.stderr)
        return 2

    if args.trace_dir is not None and not args.trace_dir.is_dir():
        print(f"error: trace dir not found: {args.trace_dir}", file=sys.stderr)
        return 2

    args.output_dir.mkdir(parents=True, exist_ok=True)

    index: dict[str, list[dict[str, Any]]] = (
        _load_definitions(args.trace_dir) if args.trace_dir else {}
    )

    text = args.log_file.read_text()
    lines = text.splitlines()

    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    seen: dict[str, set[str]] = defaultdict(set)
    n_calls = 0
    n_matched = 0

    for func_name, body in _iter_blocks(lines):
        n_calls += 1
        log_inputs: dict[str, Any] = {}
        for name, value_lines in _iter_inputs(body, args.include_defaults):
            log_inputs[name] = _parse_value_block(value_lines)

        if index:
            match = _select_match(func_name, log_inputs, index, strict_only=args.strict)
        else:
            match = None

        if match is not None:
            defn, aligned = match
            file_key, record = _build_matched_workload(defn, aligned)
            n_matched += 1
        else:
            file_key, record = _build_raw_workload(func_name, log_inputs)

        if args.dedupe:
            key_parts = (
                record.get("definition"),
                json.dumps(record["workload"].get("inputs", {}), sort_keys=True),
                json.dumps(record["workload"].get("axes", {}), sort_keys=True),
            )
            key = json.dumps(key_parts)
            if key in seen[file_key]:
                continue
            seen[file_key].add(key)

        grouped[file_key].append(record)

    if not grouped:
        print(
            "warning: no FlashInfer API call blocks found in log "
            "(is the file produced with FLASHINFER_LOGLEVEL>=3?)",
            file=sys.stderr,
        )
        return 1

    for key, records in grouped.items():
        out_path = args.output_dir / f"{_slugify(key)}.jsonl"
        with out_path.open("w") as f:
            for rec in records:
                f.write(json.dumps(rec) + "\n")

    total = sum(len(v) for v in grouped.values())
    summary = (
        f"parsed {n_calls} API call(s); "
        f"{n_matched} matched a definition, {n_calls - n_matched} emitted as raw; "
        f"wrote {total} workload entry(ies) across {len(grouped)} file(s) "
        f"in {args.output_dir}"
    )
    print(summary)
    return 0


if __name__ == "__main__":
    sys.exit(main())
